### PR TITLE
Artifact is not specified in any settings file

### PR DESCRIPTION
**Pull request by gunnargestsson**
On my fresh app folder I intend to use cloud development only and have not specified any artifact url.  That breaks the cloud environment creation script.  

I see that the script is checking if there is a test app and looks like it would like to install the Test-Runner application to the development environment.  That part is never executed for the new cloud environment.

### CODE REVIEW

**Comment by gunnargestsson** [comment]
I may need to rethink this...  This is also skipping the step in local devenv!

**Comment by gunnargestsson** [comment]
I stand corrected, the test toolkit is imported into the cloud environment.  My previous attempt did not finish the app compile.

**Comment by gunnargestsson** [comment]
Install-BcAppFromAppSource Telemetry Correlation Id: a5a71255-4794-45ec-86cf-2f1dd81de80e
Import-TestToolkitToBcContainer Telemetry Correlation Id: a348e27a-ef47-4ff6-977a-4276671be30c
Run-AlPipeline Telemetry Correlation Id: 31ba62ec-bf30-40eb-8c5f-194a36c4102c
Removing BcContainerHelper
The remote server returned an error: (400) Bad Request.  (ms-correlation-x = 11c685df-28fd-409e-a745-3508cf2378f7)
At C:\Users\gunnar\AppData\Local\Temp\cf59ca47-3d90-4143-88c4-6f4a46d5d6b1\BcContainerHelper\BcSaaS\Install-BcAppFromAppSource.ps1:76 char:13
+             throw (GetExtendedErrorMessage $_)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The remote serv...5-3508cf2378f7):String) [], RuntimeException
    + FullyQualifiedErrorId : The remote server returned an error: (400) Bad Request.  (ms-correlation-x = 11c685df-28fd-409e-a745-3508cf2378f7)

**Comment by freddydk** [comment]
All PR's needs to be on the AL-Go repo following the process described here:
https://github.com/microsoft/AL-Go/blob/main/Scenarios/Contributing.md

**Pull request closed without merging**
